[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://*.supabase.co https://*.website-files.com https://fonts.googleapis.com https://fonts.gstatic.com https://images.unsplash.com data: blob:; script-src 'self' 'unsafe-inline' https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.supabase.co https://*.website-files.com https://images.unsplash.com https://* blob:; font-src 'self' https://fonts.gstatic.com https://*.supabase.co data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.supabase.co https://fonts.googleapis.com https://fonts.gstatic.com ws://localhost:* http://localhost:* https://localhost:* https://iqqjvjzvzizrxbymrjoc.supabase.co https://*.vercel-insights.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cache-Control = "public, max-age=31536000"